#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import sys
import agent
import os

# perform the upgrade from collabora:1.0.5

# Get the ADMIN_PASSWORD environment variable
admin_password = os.getenv('ADMIN_PASSWORD')

# Define the path for the password file
password_file_path = os.path.expanduser('~/.config/state/password.env')

if admin_password:
    # Write the ADMIN_PASSWORD to the file
    password = {"ADMIN_PASSWORD": admin_password}
    agent.write_envfile("password.env", password)

    # Check if the file is not empty
    if os.path.getsize(password_file_path) > 0:
        print("Password file of collabora created", file=sys.stderr)
        agent.unset_env("ADMIN_PASSWORD")
    else:
        print(agent.SD_WARNING + "Error Password file of collabora is empty", file=sys.stderr)
        exit(1)
