#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import sys
import agent
import os

# perform the upgrade from collabora:1.0.5

# Get the ADMIN_PASSWORD environment variable
admin_password = os.getenv('ADMIN_PASSWORD')

if admin_password:
    agent.write_envfile("password.env", {"password": admin_password})
    agent.unset_env("ADMIN_PASSWORD")
