#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#
import os
import json
import sys
import agent

# Prepare return variable
config = {}
config["admin_password"] = agent.read_envfile("password.env")["ADMIN_PASSWORD"] if os.path.exists("password.env") else ""
config["host"] = os.environ.get("TRAEFIK_HOST",'')
config["http2https"] =  os.environ.get("TRAEFIK_HTTP2HTTPS","False") == "True"
config["lets_encrypt"] =  os.environ.get("TRAEFIK_LETS_ENCRYPT","False") == "True"


# Dump the configuratio to stdout
json.dump(config, fp=sys.stdout)
